### ISSUE TITLE
Where does VFS For Git Mount The Repos

### ISSUE THREAD

**Issue by jonathanchapmanmoore** [microsoft/VFSForGit#1789] opened 2022-09-12 19:56 UTC
I installed VFS for Git and where does in mount the Repos

![188249718-80d1ab57-c987-409d-beee-d9ac385da768](https://user-images.githubusercontent.com/8218836/189744055-42e59477-bfe9-4160-acc1-b92870075b98.png)

But at what location on the NTFS File System? Running Windows 10 LTSC 1809.

**Comment by derrickstolee** [comment] 2022-09-19 13:02
Duplicate of #1788

**Closed by derrickstolee** 2022-09-19 13:02 UTC
