### ISSUE TITLE
Mac: Kext didn't autoload when in /Library/Extensions

### ISSUE THREAD

**Issue by nickgra** [Microsoft/VFSForGit#705] opened 2019-01-17 19:27 UTC
From the customer's first impressions:
> Needed to manually call `sudo kextload /Library/Extensions/PrjFSKext.kext`

Maybe a reboot needs to occur for the kext to autoload? If so, maybe we need to load it as part of our postinstall script so users don't have this bad experience on their first run?

**Comment by pmj** [comment] 2019-01-17 20:32
> Maybe a reboot needs to occur for the kext to autoload?

Generally not. But the kext authorisation UI really messes with kext loading in my experience, with hard-to-reproduce one-off glitches like that.

There are a few things that can go wrong:
- The user hasn't approved the kext. To check for this, run `kextutil` or `kextload` on it, and if they report `System policy prevents loading the kernel extension.` that's the problem. The programmatic equivalent is a return value of `kOSKextReturnSystemPolicy` from the KextManager API. (Solution: direct the user to approve the kext.)
- The kext isn't added to the kext cache and IOKit matching. This can happen if there's a race between kextcache rescanning `/Library/Extensions` and the kext not being fully installed yet (and the kext thus being deemed not loadable by the kextcache scan because e.g. some files are missing or the signature doesn't validate), *or* if the mtime on `/Library/Extensions` is not updated when installing the kext. (E.g. when updating the kext using `sudo cp -r`) Neither should happen when installing using a .pkg, but I could swear kext authorisation mucks this one up occasionally. (Authorising too fast? Too slow? Who knows. I have no proof at the moment.) To check for this, again attempt to load the kext manually. If it loads, perform a `sudo touch /Library/Extensions` to force a kextcache rescan.

If explicit kext loading fails with some other error… there is some other problem. :-)

The only reliable recourse I'm aware of is to check for these conditions in the software that relies on the kext finds the kext hasn't been loaded. Loading the kext will need to be done with root privileges, so for example the log daemon could do it. However, that doesn't help for telling the user to approve the kext, plus the daemon could detect problems where there are none if it happens to be launched before the kext. So perhaps PrjFSLib could test for the error and send an IPC request to the log daemon to find out how to resolve it?

**Comment by wilbaker** [comment] 2019-02-08 17:03
@alameenshah, @nickgra, @kewillford, with Kevin's fix in #712 can we close this issue?

**Comment by alameenshah** [comment] 2019-02-12 15:49
> @alameenshah, @nickgra, @kewillford, with Kevin's fix in #712 can we close this issue?

I think #712 helps lazy load kext on-demand (in case not already loaded) and makes this issue (to load post install) un necessary.

**Comment by nickgra** [comment] 2019-02-12 18:47
I agree with @alameenshah, I think we can close this issue for now. If we have any other reports from Early Adopters, we should open another issue (and try another fix).

**Comment by wilbaker** [comment] 2019-02-12 19:29
> I agree with @alameenshah, I think we can close this issue for now. If we have any other reports from Early Adopters, we should open another issue (and try another fix).

Thanks @nickgra, I'll go ahead and close this then.

cc: @jrbriggs

**Closed by wilbaker** 2019-02-12 19:29 UTC
Labels: mac-kernel-extension, macOS
