### ISSUE TITLE
GVFS Sparse shows "Unable to communicate with GVFS" during failure because of existing file handle going out of scope

### ISSUE THREAD

**Issue by judemars** [microsoft/VFSForGit#1590] opened 2019-11-14 19:16 UTC
This is the issue we saw in our sync this morning - where I called gvfs sparse to make the nmake folder go out of scope but was in that folder, so it couldn't. It should have gracefully existed, but it showed a BrokenPipeException.

```
D:\mono\src\nmake>gvfs sparse --set otools;engtools\scoper --prune
Running git status...Succeeded
Updating sparse folder set...Succeeded
Forcing a projection change...Succeeded
Finding folders to prune...Succeeded
Found 1 folders to prune.
Running git status before prune to make sure you don't have any pending changes.
Running git status...Succeeded
WARNING: If you abort the sparse after this point, the repo may become corrupt
Unmounting...Succeeded
Cleaning up folders...-Cannot prune folder 'nmake': removing 'nmake' failed.
Ensure no applications are accessing the folder and retry.
More details: The process cannot access the file 'D:\mono\src\nmake' because it is being used by another process.
Cleaning up folders...Succeeded
Mounting...Succeeded
Unable to communicate with GVFS: GVFS.Common.NamedPipes.BrokenPipeException: Unable to read from pipe
   at GVFS.Common.NamedPipes.NamedPipeClient.ReadRawResponse()
   at GVFS.CommandLine.DehydrateVerb.SendDehydrateMessage(ITracer tracer, GVFSEnlistment enlistment, List`1 folderErrors, String[] folders) in D:\a\1\s\GVFS\GVFS\CommandLine\DehydrateVerb.cs:line 338
Failed to prune. Exit Code: GenericError
```

Then, further calls to it failed with "GVFS has not finished initializing"
```
D:\mono\src>gvfs sparse --set otools;engtools\scoper --prune
Running git status...Failed
Failed to run git status: GVFS has not finished initializing, please wait a few seconds and try again.
fatal: pre-command hook aborted command
Sparse was aborted.
```

My diagnose is at \\scratch2\scratch\judemars\gvfs_20191114_110922.zip

**Comment by wilbaker** [comment] 2019-11-21 00:23
@kewillford FYI - I am picking this work item up next.

**Comment by wilbaker** [comment] 2019-11-21 19:47
I did some digging and this:

> I called gvfs sparse to make the nmake folder go out of scope but was in that folder, so it couldn't. It should have gracefully existed, but it showed a BrokenPipeException.

Is actually a bigger issue, and it's unrelated to running `sparse` inside of a directory that is being pruned.  The problem is that when `sparse` needs to make a call to `dehydrate` a message is sent to the mount process that results in `git checkout -f HEAD` getting called:

https://github.com/microsoft/VFSForGit/blob/1fbf110dc0068070ac4282dbb03efb3309468423/GVFS/GVFS.Mount/InProcessMount.cs#L306

And that call triggers *a second* call to the post-command hook, and that second post-command hook calls `sparse` a second time and that ends up unmounting the repo and causing the broken pipe exception.

I will look into some options for preventing re-entrant calls to `gvfs sparse`

**Comment by wilbaker** [comment] 2019-11-25 18:41
@judemars @jrbriggs @kewillford marking this as closed for now.  With the changes in #1605 this shouldn't be an issue as long as `gvfs sparse` is not called in response to `git reset` (it's OK to call it in response to `reset --hard`, but not `reset (--mixed)`

**Closed by wilbaker** 2019-11-25 18:41 UTC
Labels: domain: sparse, pri1
