### ISSUE TITLE
Track what processes create folder placeholders, and log how many folders were removed during projection changes

### ISSUE THREAD

**Issue by wilbaker** [microsoft/VFSForGit#942] opened 2019-03-18 22:07 UTC
Currently VFS4G tracks which processes have been creating file placeholders (and records the top 10 in heartbeats), but it does not track what processes are creating folder placeholders.

VFS4G should start tracking both.

**Comment by nickgra** [comment] 2019-05-15 22:59
Is this a dupe of #490? @wilbaker

**Comment by wilbaker** [comment] 2019-05-15 23:10
Yep good call @nickgra.  I will close the older issue as this issue has a few more details.

**Comment by nickgra** [comment] 2019-06-05 22:44
Picking this one up per my offline conversation with @jeschu1 and @wilbaker (I have a hacky version that will be cleaned up before PR).

**Comment by nickgra** [comment] 2019-06-07 18:39
> Additionally, VFS4G should record how many empty directories it was able to delete when it updates placeholders as part of a projection change.

I have split this out into a separate issue. #1255

**Closed** 2019-06-10 23:52 UTC
Labels: affects: live-site, platform: macOS, platform: windows, pri1
